name = "taranga-plus-backend"
main = "src/api/router.ts"
compatibility_date = "2024-03-20"

[triggers]
crons = ["0 * * * *"] # Run every hour

[[kv_namespaces]]
binding = "TARANGA_KV"
id = "b0b98e15f22c4be8a25226df118b752e"
preview_id = "b0b98e15f22c4be8a25226df118b752e"
